### ISSUE TITLE
Unity Player for Windows

### ISSUE THREAD

**Issue by g38kun** [benwulfe/firebase-unity#2]
Thank you for fantastic plugin!
Would you recompile this plugin for Windows?
I tried to recompile it but it doesn't work.
> Currently, the unity player is only functional for Macs, Windows is not supported but message me if you want it (its a simple recompile)

**Comment by benwulfe** [comment]
Sure! -- give me a day or two.  It is set up to compile to a dylib and should just need a bit of refactoring and repackaging into a dll.

**Comment by groentebroer** [comment]
Hi benwulfe and g38kun, this would help us as well to speed up development, to run it locally instead of compiling it to a device every time. Would be great if you can implement it soon!

**Comment by cbrpokoj305** [comment]
hi benwulfe, i am also waiting for windows plugin... that would be great to hear something from you...

**Comment by benwulfe** [comment]
I've implemented the player for Windows (you can now hit play and use firebase within the Unity3d editor while running in Windows).  Note that its not as well tested as Android/iOS and also you will need to have Java installed and added to the path (jvm.dll must be in the path).

This does not add support for executing on Windows as a runtime platform  --only within the editor.  Let me know if I misunderstood the issue.

Also -- please get this project STAR'd if you'd like to see more support for Unity3d.  I work on the Firebase team and the more we see demand for unity, the more we'll allocate time to it.

-regards!

**Comment by g38kun** [comment]
Thanks! It's working in Unity Editor for Windows. That's will be helpful for our project.
I wish Firebase officially support Unity. Our team members will give stars to this project.
